In [158]:
#!pip install torchmetrics

import torch
from torch import nn
from torch.utils.data import DataLoader, Dataset
#from torchvision import datasets
from sklearn import datasets
#from torchvision.transforms import ToTensor, Lambda, Compose
import torchmetrics
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import numpy as np

In [167]:
data= datasets.load_wine()
Xtrain,Xtest,ytrain, ytest=train_test_split(data.data, data.target, test_size=0.3, random_state=1, shuffle=True)
print(len(Xtrain), len(Xtest))
train, test=({'X':Xtrain,'y':ytrain}, {'X':Xtest,'y':ytest})
class model(nn.Module):
  def __init__(self,in_features, out_features):
    super().__init__()
    self.in_features=in_features
    self.out_features=out_features
    self.Linear=nn.Linear(self.in_features, self.out_features)

  def forward(self, x):
    y_pred= self.Linear(x)
    return y_pred

class Data(Dataset):
  def __init__(self, sample):
    self.sample = sample
    self.x = sample['X'].astype(np.float32)
    self.y = sample['y'].astype(np.float32)

  def __getitem__(self, index):
    return (self.x[index], self.y[index])

  def __len__(self):
    return len(self.x)

124 54


In [ ]:
train_data=Data(train)
test_data=Data(test)
train_data=DataLoader(train_data, batch_size=10,shuffle=True)
test_data= DataLoader(test_data, batch_size=10,shuffle=True)
for batch in train_data:
    print(batch)
print(len(train_data))

In [169]:
epochs=100
model1=model(13,3)
criterion=nn.CrossEntropyLoss()
optim=torch.optim.Adam(model1.parameters(), lr=0.001)
for epoch in range(epochs):
  for i, (data1, label) in enumerate(train_data):
    label = label.long()
    y_pred=model1(data1)
    loss=criterion(y_pred, label)
    loss.backward()
    optim.step()
    optim.zero_grad()
    if epoch%10==0:
      print(loss.detach())

tensor(47.3194)
tensor(90.4188)
tensor(25.2163)
tensor(70.0288)
tensor(128.3939)
tensor(126.8829)
tensor(47.5440)
tensor(75.2123)
tensor(26.6710)
tensor(24.6641)
tensor(41.5581)
tensor(99.9068)
tensor(142.1788)
tensor(41.8213)
tensor(37.1582)
tensor(23.6309)
tensor(19.8550)
tensor(8.5299)
tensor(43.9531)
tensor(12.2817)
tensor(20.8172)
tensor(41.1985)
tensor(40.3858)
tensor(37.1361)
tensor(31.2372)
tensor(25.8465)
tensor(2.5648)
tensor(1.7335)
tensor(2.1499)
tensor(1.8335)
tensor(1.5102)
tensor(2.7654)
tensor(2.3934)
tensor(1.0227)
tensor(2.9574)
tensor(2.0476)
tensor(2.1488)
tensor(1.6892)
tensor(0.6685)
tensor(1.1534)
tensor(1.2993)
tensor(1.0384)
tensor(0.6756)
tensor(1.2576)
tensor(0.8850)
tensor(0.9209)
tensor(0.4025)
tensor(0.9817)
tensor(0.9963)
tensor(0.5916)
tensor(1.1728)
tensor(0.1203)
tensor(0.6053)
tensor(0.7579)
tensor(0.5397)
tensor(0.3534)
tensor(0.5102)
tensor(0.5346)
tensor(0.5121)
tensor(0.3072)
tensor(0.6666)
tensor(0.4542)
tensor(0.2463)
tensor(0.5762)
tensor(0.175

In [173]:
with torch.inference_mode():
    for i, (data1, label) in enumerate(test_data):
        label = label.long()
        ypred= model1(data1)
        soft=nn.Softmax(dim=1)
        print(soft(ypred).argmax(axis=-1))

tensor([2, 1, 0, 1, 1, 1, 0, 0, 0, 0])
tensor([2, 1, 1, 1, 1, 1, 2, 2, 1, 0])
tensor([0, 1, 2, 1, 0, 2, 0, 1, 0, 1])
tensor([1, 2, 0, 1, 0, 1, 0, 1, 2, 2])
tensor([0, 2, 0, 1, 1, 0, 1, 1, 1, 0])
tensor([1, 0, 0, 0])


In [100]:
comb={'X':data.data,'y':data.target}
comb['X'].sha

(178, 13)